### ISSUE TITLE
Error sending notifications

### ISSUE THREAD

**Issue by allexmail** [LJPc-solutions/freescout-internal-conversations-module#4]
Hi!
FreeScout 1.8.135
[Internal-conversations-module](https://resources.ljpc.network/freescout-modules/internal-conversations/latest.zip)  + [fix user search](https://github.com/LJPc-solutions/freescout-internal-conversations-module/commit/10df83f9f1e331a097dda29b2ef74d904ec2a908)
PHP 8.3.4

When creating an internal note, notifications are not sent to the email address. An error appears in the log. I do not know if this error applies to you or to FreeScout. I wrote to you just in case. Other notifications from FreeScout are sent correctly.

`Call to a member function getFirstName() on null (View: /var/www/help/resources/views/emails/user/notification.blade.php); File: /var/www/help/storage/framework/views/a0c70c7cdea1e2f1c504c59d55db0d3e5f1b8178.php (44)`

I am attaching screenshots that the notification error refers to an internal dialog.

![1](https://github.com/LJPc-solutions/freescout-internal-conversations-module/assets/161819100/a5159b43-55dc-4f11-badc-cc70d975e7fb)
![2](https://github.com/LJPc-solutions/freescout-internal-conversations-module/assets/161819100/d2b2b5de-9fc4-46d6-ae07-c26824a276f7)

**Comment by Lars-** [comment]
The module doesn't use that function for notifications. It simply sends out a new/updated note event. Freescout handles the rest. It still may have something to do with the module, but I can't find it unfortunately.
