### ISSUE TITLE
Global Mailbox "Drafts" folder gives error

### ISSUE THREAD

**Issue by dabesa** [LJPc-solutions/freescout-internal-conversations-module#7]
Dear support,
When the module is active, on the Global Mailbox, clicking "drafts" gives error:
Whoops, looks like something went wrong — check logs in /storage/logs

This is the log generated:

`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'type' in where clause is ambiguous (SQL: select `conversations`.* from `conversations` inner join `conversation_folder` on `conversations`.`id` = `conversation_folder`.`conversation_id` inner join `folders` on `conversation_folder`.`folder_id` = `folders`.`id` where `folders`.`mailbox_id` in (2, 5) and `folders`.`type` = 30 and `type` = 4 and JSON_CONTAINS(meta, '"13"', '$."internal_conversations.users"') OR JSON_CONTAINS(meta, '"16"', '$."internal_conversations.users"') OR (`conversations`.created_by_user_id = 13 AND `conversations`.state = 1)) {"userId":13,"email":"_____@____l.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'type' in where clause is ambiguous (SQL: select `conversations`.* from `conversations` inner join `conversation_folder` on `conversations`.`id` = `conversation_folder`.`conversation_id` inner join `folders` on `conversation_folder`.`folder_id` = `folders`.`id` where `folders`.`mailbox_id` in (2, 5) and `folders`.`type` = 30 and `type` = 4 and JSON_CONTAINS(meta, '\"13\"', '$.\"internal_conversations.users\"') OR JSON_CONTAINS(meta, '\"16\"', '$.\"internal_conversations.users\"') OR (`conversations`.created_by_user_id = 13 AND `conversations`.state = 1)) at /home/helpdeskwpok/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'type' in where clause is ambiguous at /home/helpdeskwpok/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'type' in where clause is ambiguous at /home/helpdeskwpok/public_html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82)`

FreeScout version: 1.8.142
Database: MySQL 
Module version: 1.0.6

**Comment by Lars-** [comment]
Thank you for reporting this issue. It will be fixed in the next release (probably today).

**Comment by Lars-** [comment]
Fixed in 1.0.7!
